"""temppatch.py —— 沙箱私有 TEMP 锚点 × pytest tmp_path 死锁修复（P0 2026-09-05）。

取证（s3c09 双项目 42 轮 26+ 失败步；tests/test_acl_sandbox_basetemp.py 实测）：

1. 沙箱把受限 shell 的 TEMP/TMP 指到 agent 私有锚点
   ``<ws>/.hiveweave/sandbox-temp/<agent_id>``（service.py ``_build_sandbox_env``）。
2. CPython >= 3.12 在 Windows 把 ``os.mkdir(path, mode != 0o777)`` 落成
   **PROTECTED DACL**（SYSTEM / Administrators / OWNER_RIGHTS 三条 Full ——
   无用户 ACE、无能力 SID、不继承锚点 DACL；实测 DACL dump 钉住）。
   pytest 的 tmp_path 工厂整条链都是这个形态
   （``_pytest/tmpdir.py`` getbasetemp:168 / mktemp:139 / make_numbered_dir:141,218
   全部 ``mkdir(mode=0o700)``）。
3. 受限令牌下该 mode 应用步骤本身即失败（实测 ``PermissionError [WinError 5]``，
   落在锚点下第一个 ``pytest-of-*`` 目录）：新目录 DACL 此刻只带
   ``temp_sid:GRANT_MASK``（0x110156，无 WRITE_DAC/READ_CONTROL 位）+ 用户
   ACE；令牌 DefaultDACL 注入的 ``temp_sid:FILE_ALL`` 实测**不**合并进目录
   DACL → restricting-SID pass 落空。即使该步骤成功，产出的 OWNER_RIGHTS
   孤岛对后续写/删同样双 pass 全落空 —— 即 s3c09 的「创建/写入 Access denied」。
4. 平台侧预先授予救不了：孤岛 DACL 在创建瞬间被整体替换，锚点 ACE 传不进；
   ``--basetemp`` 指到 TEMP 下也一样（basetemp 与每个测试目录都是 mode=0o700）。
   「可写目录 ∩ 禁触目录」死锁的准确形态 = 可写锚点 ∩ pytest 自建的
   OWNER_RIGHTS 死岛。

修复 = 两层，全部在「受限令牌 + 能力 SID + 可写锚点」既有模型内：

- **子进程 shim**（本模块 ``SHIM_SOURCE``）：把 ``sitecustomize.py`` 写进
  ``<ws>/.hiveweave/sandbox-temp/``（PROTECTED 区、无能力 SID —— agent 经
  内核不可写，防跨 agent 篡改），经 ``PYTHONPATH`` 注入受限子进程，把
  ``os.mkdir`` 的 mode 中和回 0o777 → 新目录继承父 DACL（锚点 = temp_sid +
  用户 ACE）。只影响沙箱子进程；native 路径不注入。不新增任何令牌权限
  （等价于子进程自己选择 permissive mode，内核仍按能力 SID 把关）。
- **平台侧孤岛修复**（``repair_temp_islands``）：浅层（深度 ≤3、跳过
  cache/ 巨树、节点数封顶）扫锚点子树，对缺 ACE 的存量目录 verify-then-skip
  补授 ``temp_sid``（pass-1）+ 当前用户 SID（pass-2），上一轮遗留的
  ``pytest-of-*`` 死岛即时复活。

跨平台：模块可导入（供单测 mock），win32 缺席时功能函数降级返回。
"""

from __future__ import annotations

import os
import sys
import threading

try:  # pragma: no cover - branch 由平台决定
    import win32api
    import win32security
except ImportError:  # non-Windows
    win32api = None
    win32security = None

import structlog

from hiveweave.services.acl_sandbox.errors import SandboxUnavailableError
from hiveweave.services.acl_sandbox.grant import GRANT_MASK, WriteGrant

log = structlog.get_logger(__name__)

# shim 文件固定名（site 机制约定）；目录 = sandbox-temp 根（agent 私有锚点的父）
SANDBOX_SHIM_FILENAME = "sitecustomize.py"

# 受限子进程注入的 sitecustomize（ASCII-only，避免子解释器编码差异）。
# 只中和 Windows 的 mode→DACL 应用；其余语义（路径校验/dir_fd/parents）原样。
SHIM_SOURCE = '''\
# HiveWeave ACL sandbox child shim (auto-generated by
# hiveweave.services.acl_sandbox.temppatch -- do not edit).
#
# Why: CPython >= 3.12 on Windows turns os.mkdir(path, mode != 0o777) into a
# PROTECTED DACL application (SYSTEM / Administrators / OWNER_RIGHTS, Full).
# pytest's tmp_path factory creates its whole directory chain that way
# (_pytest/tmpdir.py mkdir(mode=0o700)), which under the HiveWeave ACL
# sandbox produces OWNER_RIGHTS-only islands the write-restricted token
# cannot enter (both restricting-SID pass and normal-SID pass fail), and the
# mode-application step itself can fail outright (WinError 5).
#
# Fix: inside sandboxed children only, force mode=0o777 so new directories
# inherit the parent DACL. The security model is unchanged: writes are still
# gated by the restricted token's capability SIDs via the anchor/workspace
# grants -- this only stops the interpreter from replacing inherited ACLs,
# it grants no extra token power.
import os as _os
import sys as _sys

if _sys.platform.startswith("win") and not getattr(
    _os, "_hiveweave_mkdir_patched", False
):
    _os._hiveweave_mkdir_patched = True
    _hw_orig_mkdir = _os.mkdir

    def _hw_mkdir(path, mode=0o777, *args, **kwargs):
        return _hw_orig_mkdir(path, 0o777, *args, **kwargs)

    _os.mkdir = _hw_mkdir
'''


def shim_dir_for_temp_dir(temp_dir: str) -> str:
    """shim 目录 = sandbox-temp 根（锚点的父目录，agent 不可写的 PROTECTED 区）。"""
    return os.path.dirname(temp_dir)


def ensure_sitecustomize_shim(shim_dir: str) -> str | None:
    """把 shim 写进 *shim_dir*（幂等：内容一致则跳过）。失败返回 None（fail-soft）。

    写入走「临时文件 + os.replace」原子替换（P2 audit 2026-09-05）：同
    workspace 多 agent 并发首命令时，子解释器可能恰好在写盘窗口 import
    sitecustomize —— 直接 open("w") 会先截断后写，读到的半截文件语法错误
    被 site 静默吞掉 → 本进程无补丁。临时文件与目标同目录（同卷保证
    replace 原子性），异常时 best-effort 清掉临时残留。

    返回 shim 目录（供 ``_build_sandbox_env`` 注入 PYTHONPATH）。
    """
    try:
        os.makedirs(shim_dir, exist_ok=True)
        target = os.path.join(shim_dir, SANDBOX_SHIM_FILENAME)
        needs_write = True
        try:
            with open(target, "r", encoding="utf-8") as f:
                needs_write = f.read() != SHIM_SOURCE
        except OSError:
            pass
        if needs_write:
            tmp_path = f"{target}.tmp-{os.getpid()}"
            try:
                with open(tmp_path, "w", encoding="utf-8", newline="\n") as f:
                    f.write(SHIM_SOURCE)
                os.replace(tmp_path, target)
            except OSError:
                try:
                    os.unlink(tmp_path)
                except OSError:
                    pass
                raise
        return shim_dir
    except OSError as e:
        log.warning(
            "acl_sandbox.temp_shim_write_failed",
            shim_dir=shim_dir, error=str(e),
        )
        return None


def current_user_sid() -> str | None:
    """当前进程令牌的用户 SID（walker pass-2 补授用）。非 Windows / 失败 → None。"""
    if win32api is None or win32security is None:
        return None
    try:
        token = win32security.OpenProcessToken(
            win32api.GetCurrentProcess(), win32security.TOKEN_QUERY)
        try:
            user, _ = win32security.GetTokenInformation(
                token, win32security.TokenUser)
            return win32security.ConvertSidToStringSid(user)
        finally:
            token.Close()
    except Exception:  # noqa: BLE001 —— 探测失败降级（walker 只补 temp_sid）
        return None


# walker 扫描上限：锚点子树（pytest-of-* 链）小而浅；cache/（包管理器私有
# 缓存）可能数万文件，必须排除，节点数再兜底封顶。
_WALK_MAX_DEPTH = 3
_WALK_MAX_NODES = 256
_WALK_SKIP_DIRS = frozenset({"cache"})


def repair_temp_islands(
    temp_dir: str,
    temp_sid: str,
    user_sid: str | None,
    *,
    max_depth: int = _WALK_MAX_DEPTH,
    max_nodes: int = _WALK_MAX_NODES,
) -> int:
    """锚点子树 OWNER_RIGHTS 死岛修复（verify-then-skip）。返回实际补授次数。

    对每个目录：缺 ``temp_sid``（restricting-SID pass）或缺 ``user_sid``
    （normal-SID pass）任一 ACE → 补授。单目录失败不中断（fail-soft）。
    只动锚点子树 —— 不触碰 .hiveweave 其余 PROTECTED 区。
    """
    if win32security is None or not os.path.isdir(temp_dir):
        return 0
    sids = [temp_sid] + ([user_sid] if user_sid else [])
    repaired = 0
    visited = 0
    stack: list[tuple[str, int]] = [(temp_dir, 0)]
    while stack and visited < max_nodes:
        d, depth = stack.pop()
        visited += 1
        for sid in sids:
            try:
                if not WriteGrant.ace_present(d, sid, GRANT_MASK):
                    WriteGrant.grant_standing(d, sid, GRANT_MASK)
                    repaired += 1
            except Exception:  # noqa: BLE001 —— 单目录失败不中断
                continue
        if depth >= max_depth:
            continue
        try:
            children = [
                c for c in os.scandir(d) if c.is_dir(follow_symlinks=False)
            ]
        except OSError:
            continue
        for c in children:
            if c.name.lower() in _WALK_SKIP_DIRS:
                continue
            stack.append((c.path, depth + 1))
    return repaired


# ── P2（audit 2026-09-05）：per-anchor walker 水位（进程内） ──────────
# 稳态下 walker 每命令全跑会在边界根锁内做数百次 ACL 查询，拉长同 workspace
# 并发首命令的串行点。进程内水位：同锚点只全跑一次；probe 路径（开工/启动
# 自检）不受水位限制仍全跑。worktree 同路径重建后锚点为空目录、shim 兜住
# 新建链，无需重跑。仅内存态 —— 进程重启后首命令自然重跑（verify-then-skip）。
_repaired_anchors: set[str] = set()
_repaired_anchors_guard = threading.Lock()


def repair_temp_islands_once(
    temp_dir: str,
    temp_sid: str,
    user_sid: str | None,
    *,
    max_depth: int = _WALK_MAX_DEPTH,
    max_nodes: int = _WALK_MAX_NODES,
) -> int:
    """水位版 walker（``_ensure_temp`` 每命令路径用）：同进程同锚点只跑一次。

    水位键 = normcase(realpath(anchor))；命中直接返回 0。walker 抛异常时不记
    水位（下一命令 verify-then-skip 重试）。
    """
    key = os.path.normcase(os.path.realpath(temp_dir))
    with _repaired_anchors_guard:
        if key in _repaired_anchors:
            return 0
    repaired = repair_temp_islands(
        temp_dir, temp_sid, user_sid, max_depth=max_depth, max_nodes=max_nodes
    )
    with _repaired_anchors_guard:
        _repaired_anchors.add(key)
    return repaired


async def probe_private_temp(
    *,
    workspace_path: str,
    agent_id: str,
    project_workspace_path: str | None = None,
) -> dict:
    """开工/启动自检（fail-soft，绝不上抛）：锚点确保 + 死岛修复 + 写+删探针。

    挂点：worktree 创建（git_worktree ``_schedule_sandbox_grant``）与启动
    回填（main.py ``_acl_backfill``），均在 ``ensure_standing_grants`` 之后。
    返回结构化结果；异常/不可写只 log warning（结构化字段），不阻断。
    """
    result: dict = {
        "ok": False,
        "writable": False,
        "subject_write_ace": False,
        "repaired": 0,
        "temp_dir": None,
        "error": None,
    }
    if not sys.platform.startswith("win") or win32security is None:
        result["error"] = "non-windows or pywin32 unavailable"
        return result
    from hiveweave.config import settings

    if not settings.acl_sandbox:
        # 沙箱关闭 = 零足迹（与 ensure_standing_grants 的 no-op 纪律一致）；
        # 属配置性关闭而非故障，不打 warning。
        result["error"] = "sandbox-disabled"
        return result
    try:
        from hiveweave.services.acl_sandbox.policy import resolve_policy

        policy = resolve_policy(
            workspace_path=workspace_path, agent_id=agent_id,
            project_workspace_path=project_workspace_path,
        )
    except Exception as e:  # noqa: BLE001
        result["error"] = f"resolve_policy: {e}"
        log.warning(
            "acl_sandbox.temp_probe", agent_id=agent_id,
            workspace=workspace_path, writable=False,
            subject_write_ace=False, repaired=0, error=result["error"],
        )
        return result
    result["temp_dir"] = policy.temp_dir
    try:
        os.makedirs(policy.temp_dir, exist_ok=True)
        if not WriteGrant.ace_present(
                policy.temp_dir, policy.temp_sid, GRANT_MASK):
            WriteGrant.grant_standing(
                policy.temp_dir, policy.temp_sid, GRANT_MASK)
        try:
            result["repaired"] = repair_temp_islands(
                policy.temp_dir, policy.temp_sid, current_user_sid())
        except Exception as e:  # noqa: BLE001
            result["error"] = f"island_repair: {e}"
        # §4.12 主体探测（pass-2 前提）：锚点须带真实主体（用户）写 ACE
        result["subject_write_ace"] = WriteGrant.has_subject_write_ace(
            policy.temp_dir)
        # 平台侧「写+删」探针。P2（audit 2026-09-05）：写成功但 remove 失败
        # 时重试一次，仍失败仅记日志（可写性已由成功写入证实；残留不影响
        # ok 判定，也不上抛）。
        probe_path = os.path.join(policy.temp_dir, f".probe-{os.getpid()}")
        try:
            with open(probe_path, "w", encoding="utf-8") as f:
                f.write("probe")
            result["writable"] = True
        except OSError as e:
            result["error"] = (result["error"] or "") + f" write_probe: {e}"
        if result["writable"]:
            for attempt in (1, 2):
                try:
                    os.remove(probe_path)
                    break
                except OSError as e:
                    if attempt == 2:
                        log.warning(
                            "acl_sandbox.temp_probe_residue",
                            probe_path=probe_path, error=str(e),
                        )
        result["ok"] = bool(result["writable"] and result["subject_write_ace"])
    except SandboxUnavailableError as e:
        result["error"] = (result["error"] or "") + f" grant: {e}"
    except Exception as e:  # noqa: BLE001 —— 任何意外都不上抛
        result["error"] = (result["error"] or "") + f" {type(e).__name__}: {e}"

    if not result["ok"]:
        log.warning(
            "acl_sandbox.temp_probe", agent_id=agent_id,
            workspace=workspace_path,
            writable=result["writable"],
            subject_write_ace=result["subject_write_ace"],
            repaired=result["repaired"], error=result["error"],
        )
    elif result["repaired"]:
        log.info(
            "acl_sandbox.temp_probe_repaired", agent_id=agent_id,
            temp_dir=policy.temp_dir, repaired=result["repaired"],
        )
    return result
